### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by mohe2015** [mohe2015/Klassenmixer#53]
```
Maximum possible points: 2,000,000
First step
Groups:
[a nobody nobody nobody]
[b c nobody nobody, c bete nobody nobody, bete nobody nobody nobody]
Second step
Groups:
[a nobody nobody nobody]
[b c nobody nobody, c bete nobody nobody, bete nobody nobody nobody]
Third step
Groups:
[a nobody nobody nobody]
[b c nobody nobody, c bete nobody nobody, bete nobody nobody nobody]
Maximum possible points: 1,000,000
First step
Groups:
[a nobody nobody nobody]
[b nobody nobody nobody]
[c bete nobody nobody, bete nobody nobody nobody]
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at de.selfmade4u.klassenmixer.StudentClassMixer.generateAllPossibleClassCombinations(StudentClassMixer.java:240)
	at de.selfmade4u.klassenmixer.StudentClassMixer.createClassesFromGroups(StudentClassMixer.java:209)
	at de.selfmade4u.klassenmixer.StudentClassMixer.step1(StudentClassMixer.java:170)
	at de.selfmade4u.klassenmixer.gui.MainJFrame.lambda$onComputeBestClassCombination$17(MainJFrame.java:503)
	at de.selfmade4u.klassenmixer.gui.MainJFrame$$Lambda$17.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```
[buggy.txt](https://github.com/mohe2015/Klassenmixer/files/1245453/buggy.txt)

**Comment by mohe2015** [comment]
```
Maximum possible points: 1,000,000
First step
Groups:
[bob nobody nobody nobody]
[peter nobody nobody nobody]
[klaus nobody nobody nobody, dieter klaus nobody nobody]
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.get(ArrayList.java:323)
	at de.selfmade4u.klassenmixer.StudentClassMixer.generateAllPossibleClassCombinations(StudentClassMixer.java:240)
	at de.selfmade4u.klassenmixer.StudentClassMixer.createClassesFromGroups(StudentClassMixer.java:209)
	at de.selfmade4u.klassenmixer.StudentClassMixer.step1(StudentClassMixer.java:170)
	at de.selfmade4u.klassenmixer.gui.MainJFrame.lambda$onComputeBestClassCombination$17(MainJFrame.java:503)
	at de.selfmade4u.klassenmixer.gui.MainJFrame$$Lambda$17.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:595)
```
