### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid location

### ISSUE THREAD

**Issue by mohe2015** [mohe2015/Klassenmixer#54]
In students table add second choices. Then edit them and press backspace a few times:
```
java.lang.IllegalArgumentException: Invalid location
	at javax.swing.text.JTextComponent.getSelectedText(JTextComponent.java:1495)
	at javax.swing.text.DefaultCaret.updateSystemSelection(DefaultCaret.java:1288)
	at javax.swing.text.DefaultCaret.changeCaretPosition(DefaultCaret.java:1214)
	at javax.swing.text.DefaultCaret.handleMoveDot(DefaultCaret.java:1063)
	at javax.swing.text.DefaultCaret.moveDot(DefaultCaret.java:1057)
	at javax.swing.text.DefaultEditorKit$NextVisualPositionAction.actionPerformed(DefaultEditorKit.java:1579)
	at org.jdesktop.swingx.autocomplete.AutoCompleteDecorator$NonStrictBackspaceAction.actionPerformed(AutoCompleteDecorator.java:396)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1568)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2766)
	at javax.swing.JTable.processKeyBinding(JTable.java:3500)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2812)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2729)
	at java.awt.Component.processEvent(Component.java:5294)
	at java.awt.Container.processEvent(Container.java:1966)
	at java.awt.Component.dispatchEventImpl(Component.java:3984)
	at java.awt.Container.dispatchEventImpl(Container.java:2024)
	at java.awt.Component.dispatchEvent(Component.java:3819)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1828)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:681)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:940)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:810)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:645)
	at java.awt.Component.dispatchEventImpl(Component.java:3857)
	at java.awt.Container.dispatchEventImpl(Container.java:2024)
	at java.awt.Window.dispatchEventImpl(Window.java:1791)
	at java.awt.Component.dispatchEvent(Component.java:3819)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:463)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:163)
```

**Comment by mohe2015** [comment]
Probably bug in org.jdesktop.swingx.autocomplete.AutoCompleteDecorator
