### ISSUE TITLE
Update process fails and renders binary unusable

### ISSUE THREAD

**Issue by mohe2015** [mohe2015/Klassenmixer#55]
```
Exception in thread "main" java.lang.IllegalArgumentException
	at java.nio.Buffer.limit(Buffer.java:249)
	at sun.nio.ch.FileChannelImpl.transferFromArbitraryChannel(FileChannelImpl.java:565)
	at sun.nio.ch.FileChannelImpl.transferFrom(FileChannelImpl.java:606)
	at de.selfmade4u.klassenmixer.Main.main(Main.java:105)
```

**Comment by mohe2015** [comment]
Fix in 6ea642f541edab792018f0c1a9c8a5a61305062c
